### ISSUE TITLE
Feature: file browser in editor

### ISSUE THREAD

**Issue by TeacherTalley** [holden-davis-uca/MARS-UCA#1]
I had an idea!  What do you think about adding a file browser on the left hand side of the window of the editor similar to other IDE's such as Visual Code or Spyder?  You would definitely want to be able to hide it to increase screen real estate, but I think it that would be very useful feature.

**Comment by holden-davis-uca** [comment]
Added! (kind of). The method used by the original authors to add JPanels to the screen is _interesting_, so this is a very barebones, hacky implementation that adds another tab to the messages pane on the bottom of the screen.

At the moment, it only supports viewing folders and files in the directory Mars-UCA.jar is running in, but being able to load .asm files to be edited from the file viewer is something that can definitely be looked at in the future!

**Comment by TeacherTalley** [comment]
This is great!
